export const cl = {
  bg: "#F5F5F7",
  card: "#FFFFFF",
  stroke: "rgba(0,0,0,.10)",
  text: "rgba(0,0,0,.92)",
  muted: "rgba(0,0,0,.56)",
  red: "#C8102E",
  green: "#00864B",
  amber: "#B26A00",
  blue: "#0A66C2",
  soft: "rgba(0,0,0,.05)",
};

const FONT =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,'Apple Color Emoji','Segoe UI Emoji'";

export const S = {
  page: { minHeight: "100vh", background: cl.bg, color: cl.text, fontFamily: FONT, paddingBottom: 48 },
  shell: { maxWidth: 720, margin: "0 auto", padding: "0 16px" },
  hdr: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "18px 0 14px",
  },
  hdrTitle: { fontSize: 24, fontWeight: 800, letterSpacing: "-.02em", lineHeight: 1.15 },
  hdrSub: { fontSize: 12, color: cl.muted, marginTop: 2 },
  hdrRight: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 },
  card: {
    background: cl.card,
    border: `1px solid ${cl.stroke}`,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    boxShadow: "0 8px 24px rgba(0,0,0,.05)",
  },
  h2: { fontSize: 16, fontWeight: 800, marginBottom: 10 },
  label: { fontSize: 12, fontWeight: 700, color: cl.muted, marginBottom: 6, display: "block" },
  muted: { fontSize: 13, color: cl.muted, lineHeight: 1.45 },
  input: {
    width: "100%",
    minWidth: 0,
    padding: "11px 12px",
    borderRadius: 12,
    border: `1px solid ${cl.stroke}`,
    background: "#fff",
    color: cl.text,
    fontFamily: "inherit",
    fontSize: 16, // 16px evita el zoom automático de iOS al enfocar
    outline: "none",
  },
  row: { display: "flex", gap: 8, alignItems: "center" },
  wrap: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" },
  btn: {
    padding: "11px 16px",
    borderRadius: 12,
    border: "none",
    background: cl.red,
    color: "#fff",
    fontFamily: "inherit",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    flexShrink: 0,
  },
  btnGhost: {
    padding: "8px 12px",
    borderRadius: 10,
    border: `1px solid ${cl.stroke}`,
    background: "#fff",
    color: cl.text,
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    flexShrink: 0,
  },
  btnOff: { opacity: 0.45, cursor: "not-allowed" },
  chip: {
    padding: "7px 12px",
    borderRadius: 999,
    border: `1px solid ${cl.stroke}`,
    background: "#fff",
    color: cl.text,
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  chipOn: { background: cl.text, color: "#fff", borderColor: cl.text },
  tabs: {
    display: "flex",
    gap: 4,
    padding: 4,
    background: cl.soft,
    borderRadius: 14,
    marginBottom: 14,
  },
  tab: {
    flex: 1,
    padding: "9px 8px",
    borderRadius: 10,
    border: "none",
    background: "transparent",
    color: cl.muted,
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
  },
  tabOn: { background: "#fff", color: cl.text, boxShadow: "0 2px 8px rgba(0,0,0,.08)" },
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 999,
    background: cl.soft,
    color: cl.muted,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  warn: {
    marginTop: 10,
    padding: "10px 12px",
    borderRadius: 12,
    fontSize: 13,
    lineHeight: 1.45,
    overflowWrap: "anywhere",
  },
  toast: {
    position: "fixed",
    left: "50%",
    bottom: 24,
    transform: "translateX(-50%)",
    background: "rgba(20,20,22,.94)",
    color: "#fff",
    padding: "10px 16px",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 1000,
    maxWidth: "calc(100vw - 32px)",
    textAlign: "center",
  },
};

export const chip = (on) => (on ? { ...S.chip, ...S.chipOn } : S.chip);
